#ifndef CONSTANTS_H
#define CONSTANTS_H

enum RET_VAL {
        SUCCESS = 0,
        ERR_PROG_NOT_INIT,
        ERR_PROBE_FAILED,
        ERR_WRITE_FAILED,
        ERR_CHIP_NOT_PROBED,
        ERR_CHIP_PROBED,
        ERR_CHIP_NOT_READ,
        ERR_CHIP_NOT_VERIFIED,
        ERR_FILE_SELECTED,
        ERR_FILE_HW_XML,
        ERR_FILE_WRITE,
        ERR_MEM_ALLOC,
        ERR_DIR_NOT_SEL,
        ERR_BUF_SIZE_DIFF,
        ERR_CMD_LSPCI_NOT_EXEC,
        ERR_CMD_EDID_NOT_EXEC,
        ERR_CMD_DMI_NOT_EXEC,
        ERR_CMD_VGBABIOS_NOT_EXEC,
        ERR_CMD_TAR_PACK_NOT_EXEC,
        ERR_CMD_TAR_UNPACK_NOT_EXEC,
        ERR_CONFIG_NOT_KNOWN,
        ERR_COREBOOT_COPY_ROM,
        ERR_COREBOOT_COPY_CONFIG,
        ERR_COREBOOT_MAKE,
        ERR_COREBOOT_NEED_FACTORY_BIOS,
        ERR_COREBOOT_NOROM,
        UNKNOWN
};

#endif // CONSTANTS_H

